### ISSUE TITLE
Error handling for multi-line comments

### ISSUE THREAD

**Issue by skx** [bradford-hamilton/monkey-lang#3]
First of all cute-project, you seem to have implemented a lot of the same things as I did in [my fork](https://github.com/skx/monkey/) (specifically multi-line comments, postfix operators, etc).

Anyway I notice you don't have quite so robust error-handling, in the case of multi-line comments.

Create a simple file:

```
frodo ~ $ cat > foo.mo
/* Test
```

Now execute it:

```
   
frodo ~ $ monkey-lang ./foo.mo 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4cf1a0]

goroutine 1 [running]:
main.main()
	/home/skx/go/src/github.com/bradford-hamilton/monkey-lang/main.go:57 +0x360
```

I think you want:

```
if l.char == rune(0) {
```

Rather than this:

```
if l.char == 0 {
```

Since you're working with runes not characters, as a result of c40fb48d999513f96f0f0397e8c829b732ed6900

**Comment by bradford-hamilton** [comment]
Thanks for the feedback. I will put this on my list. The project is not intended to be used by anyone, and is entirely an educational tool for me/anyone interested so unfortunately I am not going to be actively fixing/updating anything like this, but thanks for surfacing!
