### ISSUE TITLE
When input doesn't exist ..

### ISSUE THREAD

**Issue by skx** [bradford-hamilton/monkey-lang#4]
If the input file doesn't exist you panic, which is perhaps less clean than it could be:

```
frodo ~ $ monkey-lang file/not/exists
Failure to read file ''. Err: open file/not/exists: no such file or directorypanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4cf1a0]

goroutine 1 [running]:
main.main()
	/home/skx/go/src/github.com/bradford-hamilton/monkey-lang/main.go:57 +0x360
```

**Comment by bradford-hamilton** [comment]
Thanks for the feedback. I will put this on my list. The project is not intended to be used by anyone, and is entirely an educational tool for me/anyone interested so unfortunately I am not going to be actively fixing/updating anything like this, but thanks for surfacing!
